apiVersion: 1

datasources:
  - name: FlowFinancePostgreSQL
    uid: FlowFinancePostgreSQL
    type: postgres
    access: proxy
    url: ${DATABASE_HOST}:${DATABASE_PORT}
    user: ${DATABASE_USER}
    secureJsonData:
      password: ${DATABASE_PASSWORD}
    jsonData:
      database: ${DATABASE_NAME}
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: false
